<!DOCTYPE html>
<html>
		<head>
			<meta charset="utf-8"/>
			<meta http-equiv="X-UA-Compatible" content="IE=edge"/>
			<meta name="viewport" content="width=device-width, initial-scale=1"/>
			<title>{{title}}</title>
			<link href="/css/less/bootstrap.less?a123=345" rel="stylesheet/less"/>
			<link href="/css/font-awesome.min.css" rel="stylesheet"/>
			<link href="/css/styles.css" rel="stylesheet"/>
			<script src="/js/less.min.js"></script>
		</head>
		<body>
			<div class="container">
				<nav class="navbar navbar-default">
					<div class="container-fluid">
						<div class="navbar-header">
							<button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
								<span class="sr-only"></span>
								<span class="icon-bar top-bar"></span>
								<span class="icon-bar middle-bar"></span>
								<span class="icon-bar bottom-bar"></span>
							</button>
							<a class="navbar-brand" href="/css/font-awesome.min.css"></a>
						</div>
						<div id="navbar" class="navbar-collapse collapse">
							<ul class="nav navbar-nav">{{MENU|raw}}</ul>
						</div>
					</div>
				</nav>
				<div id="main-content" class="container-fluid"></div>
			</div>
			<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
			<script src="/js/bootstrap.min.js"></script>
			<script src="/js/spin.min.js"></script>
			<script src="/js/script.js"></script>
		</body>
</html>
