-- STRUCTURAL TABLES
CREATE TABLE dom(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    type VARCHAR(120) NOT NULL,
    domId VARCHAR(120) NOT NULL,
    className VARCHAR(120) NOT NULL,
    closeTag BOOLEAN NOT NULL,
    parentDom INTEGER NOT NULL REFERENCES dom(id),
    domOrder FLOAT(2,2) DEFAULT '0.00'
);
CREATE TABLE atribute(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    value VARCHAR(120) NOT NULL
);
CREATE TABLE dom_atribute(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    idDom INTEGER NOT NULL REFERENCES dom(id),
    idAtribute INTEGER NOT NULL REFERENCES atribute(id)
);
CREATE TABLE content(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    url VARCHAR(120) NOT NULL,
    tableName VARCHAR(120) NOT NULL,
    keyName VARCHAR(120) NOT NULL,
    keyValue VARCHAR(120) NOT NULL
);
CREATE TABLE content_dom(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    idContent INTEGER NOT NULL REFERENCES content(id),
    idDom INTEGER NOT NULL REFERENCES dom(id)
);
CREATE TABLE input(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    template VARCHAR(120) NOT NULL,
    placeholder VARCHAR(120) NOT NULL
);
CREATE TABLE output(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    template VARCHAR(120) NOT NULL
);
CREATE TABLE field(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    label VARCHAR(120) NOT NULL,
    type VARCHAR(120) NOT NULL,
    defaultValue VARCHAR(255) NOT NULL,
    input INTEGER NOT NULL REFERENCES input(id),
    output INTEGER NOT NULL REFERENCES output(id),
    fieldOrder FLOAT(2,2) DEFAULT '0.00'
);
CREATE TABLE content_field(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    idContent INTEGER NOT NULL REFERENCES content(id),
    idField INTEGER NOT NULL REFERENCES field(id)
);
-- CONTENT TYPE TABLES
CREATE TABLE section(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    parentSection INTEGER NOT NULL REFERENCES section(id),
    sectionOrder FLOAT(2,2) DEFAULT '0.00',
    active BOOLEAN NOT NULL
);
CREATE TABLE text(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    body TEXT NOT NULL
);
-- SUPPORT TABLES
CREATE TABLE zone(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name varchar(255) NOT NULL,
    code varchar(8) NOT NULL,
    parent INTEGER NOT NULL REFERENCES zona(id)
);
