CREATE TABLE dom(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    type VARCHAR(120) NOT NULL,
    domId VARCHAR(120) NOT NULL,
    className VARCHAR(120) NOT NULL,
    closeTag BOOLEAN NOT NULL,
    parentDom INTEGER NOT NULL REFERENCES dom(id),
    domOrder FLOAT(2,2) DEFAULT '0.00'
);
CREATE TABLE atribute(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    name VARCHAR(120) NOT NULL,
    value VARCHAR(120) NOT NULL
);
CREATE TABLE dom_atribute(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    idDom INTEGER NOT NULL REFERENCES dom(id),
    idAtribute INTEGER NOT NULL REFERENCES atribute(id)
);
CREATE TABLE zona(
    id INTEGER PRIMARY KEY AUTO_INCREMENT NOT NULL,
    nombre varchar(255) NOT NULL,
    codigo varchar(8) NOT NULL,
    padre INTEGER NOT NULL REFERENCES zona(id)
);
